# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\3_kurs\6_sem\Kursach3\test\main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 225)
        MainWindow.setMaximumSize(QtCore.QSize(300, 225))
        # '''("background-image: url('space.jpg');")'''
        # MainWindow.setStyleSheet("background-color: #4B0082;")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-image: url('style/space300x300.jpg');")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 0, 300, 70))
        self.frame.setStyleSheet("color: #7FFFD4;\n"
                                 )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 300, 80))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Bradley Hand ITC")
        font.setPointSize(17)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")

        self.encrypt_button = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_button.setGeometry(QtCore.QRect(14, 83, 271, 51))
        self.encrypt_button.setWindowOpacity(100)
        self.encrypt_button.setStyleSheet("QPushButton {\n"
                                          # "    background-image: url('green.png');\n"   
                                          # 1
                                          "    color: #7FFFD4;\n"
                                          "    background-color: rgba(255, 190, 25, 0);\n"
                                          "    border-color: rgb(152, 251, 152);\n"
                                          "    border: 3px solid #7FFFD4;\n"
                                          "    border-radius: 25;\n"
                                          "}\n"
                                          "QPushButton:pressed {\n"
                                          "    color: #A52A2A;\n"
                                          "    background-color: rgb(223, 255, 181);\n"
                                          "    border: 3px solid #A52A2A;\n"
                                          "}")
        self.encrypt_button.setFont(font)
        self.encrypt_button.setObjectName("encrypt_button")

        self.decryption_button = QtWidgets.QPushButton(self.centralwidget)
        self.decryption_button.setGeometry(QtCore.QRect(14, 150, 271, 51))
        self.decryption_button.setStyleSheet("QPushButton {\n"
                                             # "    background-image: url('green.png');\n"    
                                             "    color: #7FFFD4;\n"
                                             "    border: 3px solid #7FFFD4;\n"
                                             "    background-color: rgba(255, 190, 25, 0);\n"
                                             "    border-color: rgb(152, 251, 152);\n"
                                             "    border-radius: 25;\n"
                                             "}\n"
                                             "QPushButton:pressed {\n"
                                             "    color: #A52A2A;\n"
                                             "    border: 3px solid #A52A2A;\n"
                                             "    background-color: rgb(223, 255, 181);\n"
                                             "}")
        self.decryption_button.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.decryption_button.setFont(font)
        self.decryption_button.setObjectName("decryption_button")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Curiosity"))
        self.label.setText(_translate("MainWindow", "Welcome to Curiosity"))
        self.encrypt_button.setText(_translate("MainWindow", "ENCRYPT"))
        self.decryption_button.setText(_translate("MainWindow", "DECRYPTION"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
